name: Demo Job
run-name: This action has been run

on: [push]

jobs: 
  demo_job:
    runs-on: ubuntu latest
    steps: 
      - run: echo "hello world!"
      
      - name: Checkout
        uses: actions/checkout@v6.0.0
      
